version: "3.9"

networks:
  vpc_public:
  vpc_private:

services:

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"

    environment:
      - SERVICES=apigateway,cloudwatch,logs,sns,iam
      - AWS_DEFAULT_REGION=us-east-1
    
    networks:
      - vpc_private

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=stackshaper

    ports:
      - "5432:5432"
    
    networks:
      - vpc_private
      